---

- include: setup-debian.yml
  when: ansible_os_family == 'Debian'

  #- name: jf.php | main | template main config
  #  template: src=nginx.conf.j2 dest=/usr/local/openresty/nginx/conf/nginx.conf
  #  notify:
  #    - reload nginx
